Inline the composer installer

diff --git a/hack-lint-test/action.yml b/hack-lint-test/action.yml
--- a/hack-lint-test/action.yml
+++ b/hack-lint-test/action.yml
@@ -32,14 +32,30 @@ runs:
       shell: bash
       run: |
         hhvm --version
-        pwd
-        echo ${{github.action_path}}
-        apt update
-        apt install tree
-        tree ${{github.action_path}}
     - name: Install Composer
       shell: bash
-      run: ${{github.action_path}}/install-composer.sh --install-dir=${{runner.temp}}
+      run: |
+        echo "::group::Install Composer"
+
+        EXPECTED_CHECKSUM="$(wget -q -O - https://composer.github.io/installer.sig)"
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+
+        if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
+        then
+            >&2 echo 'ERROR: Invalid installer checksum'
+            rm composer-setup.php
+            exit 1
+        fi
+
+        php composer-setup.php --install-dir=${{runner.temp}}
+        RESULT=$?
+        rm composer-setup.php
+
+        echo "::endgroup::"
+
+        exit $RESULT
+
     - name: Install Watchman
       shell: bash
       run: ${{github.action_path}}/install-watchman.sh
